#!/bin/bash
#set -e

#Check if the input arguments are base64 encoded
B64CHECK="^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?$"

if [[ -z $1 ]]; then echo "Cannot run without arguments"; exit 1; fi
if [[ $# < 4 ]]; then echo "One or more crunner arguments is missing!"; exit 2; fi
if [[ ! $1 =~ $B64CHECK ]]; then echo "The command or engine must be base64 encoded!"; exit 3; fi
if [[ ! $2 =~ $B64CHECK ]]; then echo "The arguments must be base64 encoded!"; exit 4; fi
if [[ ! $3 =~ $B64CHECK ]]; then echo "The extension must be base64 encoded!"; exit 5; fi
if [[ ! $4 =~ $B64CHECK ]]; then echo "The code must be base64 encoded!"; exit 6; fi

#Define the variable that represents the engine binary name
COMMAND=$(echo $1 | base64 -d)
ARGS=$(echo $2 | base64 -d)
EXT=$(echo $3 | base64 -d)
CODEB64=$4
CODE="$(echo $CODEB64 | base64 -d)"

#Generate a UUID
UUID=$(uuidgen -r)

#Collection PATH
COLLECTION="$HOME/.coderuns/$COMMAND"
CODEFILE="$COLLECTION/$UUID/code.$EXT"
CODEB64FILE="$COLLECTION/$UUID/code.b64.$EXT"
CODEERRFILE="$COLLECTION/$UUID/code.$EXT.err"
CODERESJSON="$COLLECTION/$UUID/code.$EXT.result.json"
CODETIMJSON="$COLLECTION/$UUID/code.$EXT.time.json"
RECEIVEDARGS="$COLLECTION/$UUID/crunner.received.args.log"

#Create code collection folder
mkdir -p $COLLECTION/$UUID

#Echoes the received arguments to a log file
echo $# $@ > $RECEIVEDARGS

#Generates a file on the temp dir of the remote host enconded in b64
echo "$CODEB64" > $CODEB64FILE

#Convert the encoded b64 a code file on the username home directory
echo "$CODE" > $CODEFILE

#Execute the code using its engine and arguments
#time $(echo $COMMAND) {{ capsule.args }} $COLLECTION/$UUID/code.{{ capsule.ext }}


#CODE=$1
{ time $(echo $COMMAND $ARGS) $CODEFILE > $CODERESJSON; } 2> $CODEERRFILE

CHKERR=$(wc -l $CODEERRFILE | awk '{print $1}')

if [ $CHKERR == 4 ]; then

    sed -i 's/\t/,/g;/^$/d' $CODEERRFILE

    awk -F, '{ print "{\""$1"\""":" "\""$2"\"}"}' $CODEERRFILE | jq -s add > $CODETIMJSON

    #jq --argjson time "$(<$CODE.time.json)" '.time += [$time]' $CODE.result.json

    #com uuid
#    jq --arg uuid "$UUID" --argjson time "$(<$CODETIMJSON)" '.time += [$time] | .uuid += $uuid' $CODERESJSON
    echo "{}" | jq --arg uuid "$UUID" --argjson output "$(<$CODERESJSON)" --argjson time "$(<$CODETIMJSON)" '.output += $output | .time += $time | .uuid += $uuid'

    #rm $CODE.time.json $CODE.result.json $CODE.time.txt
    #Comments
else
    >&2 cat $CODEERRFILE
fi